#!/usr/bin/env node
/* Turn tools/scene.json into assets/js/scene-data.js with every asset embedded.
 * The artifact host blocks external images outright, and these are created at
 * runtime by scene-build.js, so the HTML inliner never sees them — they have
 * to travel inside the data file or the scene silently renders empty. */
const fs = require('fs'), path = require('path');
const ROOT = path.join(__dirname, '..');
const scene = JSON.parse(fs.readFileSync(ROOT + '/tools/scene.json', 'utf8'));
const MIME = { '.svg':'image/svg+xml', '.webp':'image/webp', '.png':'image/png' };

let total = 0;
scene.pieces.forEach(p => {
  const f = ROOT + '/assets/scene/' + p.file;
  if (!fs.existsSync(f)) throw new Error('missing asset: ' + p.file);
  const buf = fs.readFileSync(f);
  total += buf.length;
  p.src = 'data:' + MIME[path.extname(f)] + ';base64,' + buf.toString('base64');
});

fs.writeFileSync(ROOT + '/assets/js/scene-data.js',
  "/* Generated by tools/build_scene_data.js from the owner's composed file.\n" +
  "   Do not hand-edit: re-run tools/extract_layers.js when he sends a new\n" +
  "   export, then this. Assets are embedded because the artifact host blocks\n" +
  "   external images and these are created at runtime. */\n" +
  'window.H19_SCENE_DATA = ' + JSON.stringify(scene) + ';\n');

console.log(scene.pieces.length + ' assets embedded, ' + Math.round(total/1024) + ' KB raw');
console.log('assets/js/scene-data.js ' +
  Math.round(fs.statSync(ROOT + '/assets/js/scene-data.js').size/1024) + ' KB');
