#!/usr/bin/env node
/* The extracted centrelines, as one script the page can carry. */
const fs = require('fs');
const out = {};
for (const f of fs.readdirSync('build/v2/paths').sort()) {
  if (!f.endsWith('.json')) continue;
  const d = JSON.parse(fs.readFileSync('build/v2/paths/' + f, 'utf8'));
  out[d.section] = { hw: d.secHoverW, w: d.roadW, p: d.points };
}
fs.writeFileSync('build/v2/paths.js',
  '/* GENERATED by tools/make_paths.js from build/v2/paths/*.json.\n'
  + '   Each section: hw = its height over its width, w = his road width as a\n'
  + '   share of the section width, p = the centreline in section percentages. */\n'
  + 'window.H19_PATHS=' + JSON.stringify(out) + ';\n');
console.error('paths.js  ' + (fs.statSync('build/v2/paths.js').size/1024).toFixed(1) + 'KB');
