#!/usr/bin/env node
/* HIS FOUR PALMS, LIFTED OUT OF THE DRIVING VIEW.
 *
 * Highway_PPV.svg is 1.3MB and 5,267 shapes, and it is worth knowing where
 * that goes before deciding anything: 4,112 of those shapes - seventy-eight
 * percent of the file - are the GANTRY TRUSS, drawn as Illustrator blends,
 * 514 shapes per cell for a piece of chrome the page already has as a tile.
 * The sky, the ocean, the grass and the road are four flat shapes that a CSS
 * gradient does for nothing. What is actually worth keeping is the palms.
 *
 * There are nine in his file and four distinct trees among them, each 50 to
 * 74 shapes. They come out here as <symbol>s so the scene can plant as many
 * as it likes for the cost of a <use>, which is a reference and not a copy.
 *
 * Only the gradients each palm actually reaches are carried across - his defs
 * hold 611 of them, nearly all for the truss - and the ids are prefixed so a
 * page that already has a linear-gradient-3 keeps its own.
 */
const { chromium } = require('/home/user/storyboard-app/node_modules/playwright');
const fs = require('fs'), path = require('path');
const DIR = path.join(__dirname, '..', 'assets', 'v2', 'section-05');

/* his indices, read off the one group that holds the scene. 14/16 are the
   same tree and so are 15/17, 18/20/22 and 19/21/29 - four trees, nine
   plantings. */
const TYPES = [[14, 'a'], [15, 'b'], [18, 'c'], [19, 'd']];

(async () => {
  const br = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
  const p = await br.newPage();
  await p.setContent('<body>' + fs.readFileSync(path.join(DIR, 'highway-ppv-src.svg'), 'utf8') + '</body>');
  const out = await p.evaluate(TYPES => {
    const svg = document.querySelector('svg');
    let g = svg.querySelector('g');
    while (g && [...g.children].filter(c => c.tagName === 'g').length < 5) {
      const next = [...g.children].find(c => c.tagName === 'g'); if (!next) break; g = next;
    }
    const kids = [...g.children];
    const syms = [], defs = [];
    const seen = new Set();
    /* every url(#id) a subtree reaches, following Illustrator's href chains */
    const collect = el => {
      const ids = new Set();
      const scan = n => {
        for (const a of n.attributes || [])
          (a.value.match(/url\(#([^)]+)\)/g) || []).forEach(u => ids.add(u.slice(5, -1)));
        [...n.children].forEach(scan);
      };
      scan(el);
      for (const id of [...ids]) {
        let d = document.getElementById(id), hops = 0;
        while (d && hops++ < 5) {
          if (!seen.has(d.id)) { seen.add(d.id); defs.push(d.outerHTML) }
          const h = d.getAttribute('xlink:href') || d.getAttribute('href');
          if (!h) break;
          d = document.getElementById(h.slice(1));
        }
      }
    };
    for (const [i, name] of TYPES) {
      const c = kids[i], b = c.getBBox();
      collect(c);
      syms.push('  <symbol id="palm-' + name + '" viewBox="' +
        [b.x, b.y, b.width, b.height].map(v => +v.toFixed(2)).join(' ') + '">\n    ' +
        c.innerHTML.replace(/\n\s+/g, '\n    ') + '\n  </symbol>');
    }
    return { syms, defs, ratios: TYPES.map(([i, n]) => { const b = kids[i].getBBox();
      return n + ':' + (b.width / b.height).toFixed(3) }) };
  }, TYPES);
  await br.close();

  /* his ids are generic - linear-gradient-3 and the like - and this file is
     inlined into a page that has its own. Prefixed, references and all. */
  let text = '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"' +
    ' width="0" height="0" style="position:absolute" aria-hidden="true">\n' +
    '  <!-- GENERATED by tools/make_palms.js from his Highway_PPV.svg. Four trees\n' +
    '       as symbols; the scene plants them with <use>. -->\n' +
    '  <defs>\n    ' + out.defs.join('\n    ') + '\n  </defs>\n' +
    out.syms.join('\n') + '\n</svg>\n';
  text = text.replace(/(id="|url\(#|href="#)([A-Za-z_][\w.-]*)/g,
    (m, pre, id) => id.startsWith('palm-') ? m : pre + 'pv-' + id);

  fs.writeFileSync(path.join(DIR, 'palms.svg'), text);
  const n = (text.match(/<(path|rect|polygon|circle|ellipse)\b/g) || []).length;
  console.log('palms.svg  ' + (text.length / 1024).toFixed(1) + ' KB, ' + n + ' shapes, ' +
    out.defs.length + ' gradients kept of 611;  aspect ' + out.ratios.join(' '));
})();
