#!/usr/bin/env node
/* THE DRIVE, FOLDED INTO THE PAGE.
 *
 * build/v2/drive.html stays the one source - it is what gets iterated on and
 * what dist/drive.html is built from - and this cuts it into the three pieces
 * the page needs:
 *
 *   section-07.css   its styles, every selector scoped under .sec7
 *   section-07.html  its markup, wrapped in <section class="sec7 runway">
 *   drive.js         its script, which does nothing if .sec7 is not there
 *
 * SCOPING IS THE WHOLE JOB. Standing alone the drive owns names like .sky,
 * .copy and .page-wide element rules; dropped into a page that already has a
 * .copy and a .mode-switch they would collide, so every selector is rewritten
 * to sit inside .sec7 and the prototype's own furniture - the read-out, the two
 * probes, its standalone switch - is left behind.
 */
const fs = require('fs'), path = require('path');
const DIR = path.join(__dirname, '..', 'build', 'v2');
const src = fs.readFileSync(path.join(DIR, 'drive.html'), 'utf8');

/* the three blocks of the prototype */
const css = src.match(/<style>([\s\S]*?)<\/style>/)[1];
const js = src.match(/<script>([\s\S]*?)<\/script>\s*$/m)[1];
const runway = src.match(/<div class="runway">[\s\S]*?\n<\/div>/)[0];
const art = src.match(/<div id="art" hidden>[\s\S]*?<\/div>/)[0];

/* ---- css ------------------------------------------------------------------
 * Rewrite a selector so it lives inside the section. A :root[...] prefix has
 * to stay OUTSIDE - the mode is set on the document, not on the section - so
 * .sec7 is inserted after it rather than in front of it. */
const DROP = /^(html|body|\.hud|\.hud .*|\.toggle|\.toggle .*|\.hint|\.hint\.gone|\.mode-switch|\.mode-switch.*)$/;
const scope = sel => {
  sel = sel.trim();
  if (!sel || sel.startsWith('@')) return sel;
  if (DROP.test(sel)) return null;
  if (sel === '.runway') return '.sec7';
  if (sel.startsWith('.runway ')) return '.sec7 ' + sel.slice(8);
  const m = sel.match(/^(:root(?:\[[^\]]*\])*(?::not\([^)]*\))*)\s+(.*)$/);
  if (m) return m[1] + ' .sec7 ' + m[2];
  if (/^:root/.test(sel)) return sel;          /* a bare :root rule: variables */
  return '.sec7 ' + sel;
};

let out = '', i = 0;
while (i < css.length) {
  const open = css.indexOf('{', i);
  if (open < 0) { out += css.slice(i); break; }
  /* everything since the last rule is comment + selector */
  const head = css.slice(i, open);
  const ce = head.lastIndexOf('*/'), be = head.lastIndexOf('}');
  const cut = Math.max(ce >= 0 ? ce + 1 : -1, be);
  const lead = head.slice(0, cut + 1), selector = head.slice(cut + 1);
  /* the body, to its matching close */
  let depth = 1, j = open + 1;
  while (j < css.length && depth) { if (css[j] === '{') depth++; if (css[j] === '}') depth--; j++; }
  const body = css.slice(open, j);
  const sels = selector.split(',').map(scope).filter(Boolean);
  if (sels.length) out += lead + sels.join(',\n') + body;
  else out += lead.replace(/[^\n]/g, '') ;     /* keep the line count, drop the rule */
  i = j;
}

fs.writeFileSync(path.join(DIR, 'section-07.css'),
  '/* GENERATED by tools/make_section_07.js from drive.html - do not edit.\n' +
  '   Every selector is scoped under .sec7; the prototype\'s read-out, probes\n' +
  '   and standalone switch are left behind. */\n' + out.trim() + '\n');

/* ---- markup --------------------------------------------------------------- */
fs.writeFileSync(path.join(DIR, 'section-07.html'),
  '<!doctype html>\n<meta charset="utf-8">\n' +
  '<title>Highway 19 &mdash; section seven</title>\n' +
  '<link rel="stylesheet" href="section-fonts.css">\n' +
  '<link rel="stylesheet" href="section-07.css">\n' +
  '<style>body{margin:0}</style>\n\n' +
  '<!-- GENERATED by tools/make_section_07.js from drive.html - do not edit. -->\n' +
  /* the art block goes INSIDE the section: make_page.js takes the first
     <section> and nothing else, so anything outside it never reaches the page */
  runway.replace('<div class="runway">', '<section class="sec7 runway">')
        .replace(/<\/div>$/, art + '\n</section>') + '\n\n' +
  '<script src="drive.js" defer></script>\n');

/* ---- script --------------------------------------------------------------- */
fs.writeFileSync(path.join(DIR, 'drive.js'),
  '/* GENERATED by tools/make_section_07.js from drive.html - do not edit.\n' +
  ' * Wrapped and guarded: on a page without the section it returns at once. */\n' +
  '(function(){\nif(!document.querySelector(\'.runway\')) return;\n' + js + '\n})();\n');

const kb = f => (fs.statSync(path.join(DIR, f)).size / 1024).toFixed(1) + 'K';
console.log('section-07.css  ' + kb('section-07.css'));
console.log('section-07.html ' + kb('section-07.html'));
console.log('drive.js        ' + kb('drive.js'));
