#!/usr/bin/env node
/* page.html was a hand-copy of both sections, so an edit to a section could
 * land in one file and not the other — which is exactly what happened to the
 * road join. It is now generated: the sections are the source, this is output.
 *
 *   node tools/make_page.js            rebuilds build/v2/page.html
 */
const fs = require('fs'), path = require('path');
const DIR = path.join(__dirname, '..', 'build', 'v2');

const files = fs.readdirSync(DIR).filter(f => /^section-\d\d\.html$/.test(f)).sort();
const parts = files.map(f => {
  const html = fs.readFileSync(path.join(DIR, f), 'utf8');
  const m = html.match(/<section\b[\s\S]*<\/section>/);
  if (!m) throw new Error(f + ': no <section> found');
  return m[0];
});

const out =
'<!doctype html>\n<meta charset="utf-8">\n' +
'<meta name="viewport" content="width=device-width,initial-scale=1">\n' +
'<title>Highway 19 Rebuild</title>\n' +
'<!-- GENERATED by tools/make_page.js from ' + files.join(', ') + ' - do not edit. -->\n' +
'<!-- Both families are his own files, self-hosted. No external font requests. -->\n' +
'<link rel="stylesheet" href="section-fonts.css">\n' +
files.map(f => '<link rel="stylesheet" href="' + f.replace('.html','.css') + '">').join('\n') +
'\n<link rel="stylesheet" href="parallax.css">\n'
  + '<link rel="stylesheet" href="night.css">\n' +
'<link rel="stylesheet" href="traffic.css">\n' +
'<link rel="stylesheet" href="sun.css">\n' +
/* last, so a phone rule beats every desktop one it has to */
'<link rel="stylesheet" href="mobile.css">\n' +
'<style>body{margin:0;background:#04264f}\n' +
'/* the sections stack with nothing between them: each is a fixed ratio of the\n' +
'   same width, so the join is exact at every screen size */\n' +
'section{display:block}\n' +
'/* A HAIRLINE OF OVERLAP. Two boxes that share an edge land on a half device\n' +
'   pixel at some widths and zooms, and the row where they meet renders lighter\n' +
'   than either - a bright line straight across his ocean on his screen, though\n' +
'   not on mine at the same width. A pixel of overlap means no shared edge to\n' +
'   land badly. Sections that already ride up over the one above keep their own\n' +
'   margin: a class beats this. */\n' +
'section + section{ margin-top:-1px }</style>\n\n' +

  /* THE STORY STARTS AT NIGHT. Inline and first, because a deferred script
     runs after the first paint and the page would flash daylight before it
     got dark. data-dawn is the drive's cue to keep its hands off the mode
     until the sun is up. */
  '<!-- The page opens black and comes up into day - .dawn in night.css, the storyline in mode.js. -->\n' +
  '<script>var r=document.documentElement;r.dataset.mode=\'night\';r.dataset.dawn=\'1\'</script>\n' +
  '<div class="dawn" aria-hidden="true"></div>\n\n' +
parts.join('\n\n') +
  '\n\n<!-- HIS TEMPORARY DAY/NIGHT SWITCH. Both icons ship; night.css decides which\n' +
  '     one shows, by the same selectors that decide the palette, so the button\n' +
  '     can never disagree with the page. -->\n' +
  '<button class="mode-switch" type="button" aria-label="Switch to night">\n' +
  '  <img class="to-night" src="../../assets/v2/ui-moon.svg" alt="" width="38" height="38">\n' +
  '  <img class="to-day" src="../../assets/v2/ui-sun.svg" alt="" width="38" height="38">\n' +
  '</button>'
  + '\n\n<script src="parallax.js" defer></script>\n'
  /* his vehicles and his road, then the traffic that drives on it - in that
     order, because traffic.js reads both at start-up */
  + '<script src="sprite.js" defer></script>\n'
  + '<script src="shades.js" defer></script>\n'
  + '<script src="paths.js" defer></script>\n'
  + '<script src="traffic.js" defer></script>\n'
  + '<script src="mode.js" defer></script>\n'
  /* his traffic tuner, beside the switch - a dev panel that reads and writes
     the live simulation; it comes out with the numbers he settles on */
  + '<script src="tuner.js" defer></script>\n'
  /* the drive, last: it measures the section it lives in, so everything above
     it has to have laid out first */
  + '<script src="drive.js" defer></script>\n';

fs.writeFileSync(path.join(DIR, 'page.html'), out);
console.log('page.html <- ' + files.join(' + '));
