#!/usr/bin/env node
/* HIS CAR SHADOWS, cut to the ten the traffic actually uses.
 *
 * He drew them on the SAME ARTBOARD as the cars - every one of the twenty is
 * registered to the car it belongs to within 0.00 user units, checked - so a
 * shadow needs no offset of its own: it takes the car's transform exactly and
 * the sun's displacement is added in screen space, which is what keeps every
 * shadow on the road pointing the same way however the car is turned.
 *
 * His shapes carry no fill at all, so they render black already. Nothing here
 * flattens or recolours anything; it only picks the ten out and renames their
 * ids so a shadow and its car can both be in the document at once.
 *
 *   node tools/make_shades.js > build/v2/shades.js
 */
const fs = require('fs');
const KEEP = process.argv.slice(2).length ? process.argv.slice(2) : [
  'Green_Car', 'Grey_Sadan', 'Red_Van', 'Brown_Jeep', 'Semitrailer',
  'Blue_Minivan', 'Yellow_Cab', 'Red_Sports_car', 'Blue_bus', 'Grey_Minivan'];

const src = fs.readFileSync('assets/art/car-shadows.svg', 'utf8');

function take(id) {
  const m = new RegExp('<g id="' + id + '"[^>]*>').exec(src);
  if (!m) throw new Error('no vehicle named ' + id);
  let depth = 1;
  const re = /<g\b[^>]*?(\/?)>|<\/g>/g;
  re.lastIndex = m.index + m[0].length;
  let t;
  while ((t = re.exec(src))) {
    if (t[0].startsWith('</g')) { if (--depth === 0) return src.slice(m.index, re.lastIndex); }
    else if (!t[1]) depth++;
  }
  throw new Error('unterminated ' + id);
}

const body = KEEP.map(id => take(id)
  /* only the vehicle's OWN id is renamed - his inner groups carry ids too and
     renaming those would break nothing but would make the diff unreadable */
  .replace('<g id="' + id + '"', '<g id="' + id + '_shade"'))
  .join('\n')
  .replace(/\s+data-name="[^"]*"/g, '')
  .replace(/\s*\n\s*/g, '');

process.stdout.write('/* GENERATED by tools/make_shades.js - do not hand-edit.\n'
  + '   His own shadow silhouettes for ' + KEEP.length + ' of the twenty vehicles,\n'
  + '   drawn on the same artboard as the cars so they need no offset of their own. */\n'
  + 'window.H19_SHADES=`' + body + '`;\n');
