#!/usr/bin/env node
/* HIS SECOND SIGN, REDRAWN - and the day file written from the night one.
 *
 * Our_sign_update.svg is not a recolour, it is a REDESIGN: the board keeps its
 * width but takes the hero sign's height, and a REST AREA banner arrives over
 * its left shoulder with the shield on it, exactly the way the hero sign is
 * built. He sent it in his night colours, so this is the direction the two
 * files were written in - night first, day derived - which is the opposite of
 * everywhere else on the page and the reason it is generated rather than
 * hand-kept: his greens and his golds are ramps in the night file, and the day
 * values are the two flat colours those ramps stand in for.
 *
 * WHAT IS TAKEN AND WHAT IS NOT. His group holds the sign; the file around it
 * also holds the gantry truss, the light fittings and their beams. The page
 * already draws all three - the truss as a repeating tile, the fittings and
 * beams as .signlamps over the board - so only the sign itself comes across.
 * His board copy stays out too: it is HTML on the page so it can be selected,
 * translated and read aloud. His REST AREA label does come across as SVG text,
 * because that is how the hero sign's banner is set and the two should match.
 *
 * THE SHIELD IS A REFERENCE, NOT A COPY. His file embeds it at 711 square and
 * it is drawn 107 wide; the same PNG is already inside hero-sign.svg. It is
 * lifted out once to assets/v2/ui-shield.webp at 384 - four times the size it
 * is ever drawn - which is 25KB against his 206KB of base64.
 */
const fs = require('fs'), path = require('path');
const DIR = path.join(__dirname, '..', 'assets', 'v2', 'section-04');
const src = fs.readFileSync(path.join(DIR, 'our-sign-src.svg'), 'utf8');

/* his night ramps, and the flat day colour each one stands for */
const DAY = { 'linear-gradient-17': '#1c9022', 'linear-gradient-18': '#ffda00' };

const grab = (re, what) => { const m = re.exec(src); if (!m) throw new Error('his file no longer has ' + what); return m[0] };
const rect = (x, what) => grab(new RegExp('<rect x="' + x + '"[^>]*>'), what);

const board   = rect('1',      'the board backing');
const face    = rect('\\.53',  'the board');
const banBack = rect('46\\.53','the banner backing');
const banner  = rect('47\\.28','the banner');
const arrow   = grab(/<g>\s*<path d="M191\.82[\s\S]*?<\/g>/, 'the arrow');
const label   = grab(/<text transform="translate\(180\.27[\s\S]*?<\/text>/, 'the REST AREA label');
const shield  = grab(/<image width="711"[^>]*?\/>/, 'the shield');

const flat = s => s.replace(/url\(#(linear-gradient-\d+)\)/g, (m, id) => {
  if (!DAY[id]) throw new Error('no day colour for ' + id);
  return DAY[id];
});

/* his box: the backing rect's own edges, plus the half of its 2-wide stroke
   that falls outside, and up to the top of the shield */
const W = 858.12, H = 371.25;

fs.writeFileSync(path.join(DIR, 'our-sign.svg'),
`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">
  <!-- GENERATED by tools/make_our_sign.js from our-sign-src.svg, which is his
       own Our_sign_update.svg. Day colours; night.css switches the two fills
       back to the ramps he drew. Do not edit - re-run the tool. -->
  <g id="our-sign-Our_sign" data-name="Our sign">
    <g>
      ${flat(board)}
      ${flat(face)}
      ${arrow.replace(/\n\s+/g, '\n        ')}
    </g>
    ${flat(banBack)}
    ${flat(banner)}
    ${shield.replace(/xlink:href="[^"]*"/, 'xlink:href="../../assets/v2/ui-shield.webp"')}
    ${label.replace(/font-family="[^"]*"/, 'font-family="Be Vietnam Pro, Arial, sans-serif"')}
  </g>
</svg>
`);
/* --- AND HIS OWN FITTINGS AND BEAMS FOR THIS SIGN ------------------------
   The gantry's rig does not fit this one: he has four fittings under the
   board and two over it, but two of the six sit at the board's right-hand
   end rather than its corners, and two more hang on the banner. So this sign
   takes its own pair of overlays rather than the hero's.

   They are emitted in HIS OWN COORDINATES - the same box as the sign above,
   since both come out of the same file - which means the overlay needs no
   offsets at all: same element box, 100% by 100%. Every beam lands inside it
   (x 2 to 837 of 858, y 51 to 359 of 371), so nothing is clipped. */
const fixtures = [...src.matchAll(/<g>\s*(?:<rect x="[\d.]+" y="[\d.]+" width="[\d.]+" height="[\d.]+"[^>]*>\s*){2}<\/g>/g)]
  .map(m => m[0]).filter(g => /y="(35[0-9]|7[0-9]|4[0-9])/.test(g));
const beams = [...src.matchAll(/<polygon[^>]*fill="url\(#linear-gradient-2[0-6]\)"[^>]*\/>|<polygon[^>]*fill="url\(#linear-gradient-19\)"[^>]*\/>/g)].map(m => m[0]);
const defs = [...src.matchAll(/<linearGradient id="linear-gradient-(?:19|2[0-6])"[\s\S]*?<\/linearGradient>|<linearGradient id="linear-gradient-(?:19|2[0-6])"[^>]*\/>/g)].map(m => m[0]);
if (fixtures.length !== 8) throw new Error('expected 8 fittings, found ' + fixtures.length);
if (beams.length !== 8) throw new Error('expected 8 beams, found ' + beams.length);

const wrap = (name, body, head) => {
  fs.writeFileSync(path.join(DIR, name),
`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">
  <!-- GENERATED by tools/make_our_sign.js from his own Our_sign_update.svg. -->
${head}  ${body.join('\n  ')}
</svg>
`);
  return (fs.statSync(path.join(DIR, name)).size / 1024).toFixed(1) + 'K';
};
const f = wrap('our-sign-fixtures.svg', fixtures, '');
const b = wrap('our-sign-beams.svg', beams, '  <defs>\n    ' + defs.join('\n    ') + '\n  </defs>\n');

console.log('our-sign.svg ' + W + ' x ' + H + ', ' +
  (fs.statSync(path.join(DIR, 'our-sign.svg')).size / 1024).toFixed(1) + ' KB;  ' +
  'fixtures ' + f + ', beams ' + b);
