#!/usr/bin/env node
/* page.html was a hand-copy of both sections, so an edit to a section could
 * land in one file and not the other — which is exactly what happened to the
 * road join. It is now generated: the sections are the source, this is output.
 *
 *   node tools/make_page.js            rebuilds build/v2/page.html
 */
const fs = require('fs'), path = require('path');
const DIR = path.join(__dirname, '..', 'build', 'v2');

const files = fs.readdirSync(DIR).filter(f => /^section-\d\d\.html$/.test(f)).sort();
const parts = files.map(f => {
  const html = fs.readFileSync(path.join(DIR, f), 'utf8');
  const m = html.match(/<section\b[\s\S]*<\/section>/);
  if (!m) throw new Error(f + ': no <section> found');
  return m[0];
});

const out =
'<!doctype html>\n<meta charset="utf-8">\n' +
'<meta name="viewport" content="width=device-width,initial-scale=1">\n' +
'<title>Highway 19 Rebuild</title>\n' +
'<!-- GENERATED by tools/make_page.js from ' + files.join(', ') + ' - do not edit. -->\n' +
'<!-- Both families are his own files, self-hosted. No external font requests. -->\n' +
'<link rel="stylesheet" href="section-fonts.css">\n' +
files.map(f => '<link rel="stylesheet" href="' + f.replace('.html','.css') + '">').join('\n') + '\n' +
'<style>body{margin:0;background:#04264f}\n' +
'/* the sections stack with nothing between them: each is a fixed ratio of the\n' +
'   same width, so the join is exact at every screen size */\n' +
'section{display:block}</style>\n\n' +
parts.join('\n\n') + '\n';

fs.writeFileSync(path.join(DIR, 'page.html'), out);
console.log('page.html <- ' + files.join(' + '));
