#!/usr/bin/env node
/* His twenty vehicles, cut down to the ones the traffic actually uses.
 *
 * The full sprite is 149KB of inline SVG. Ten of them is half that, and the
 * road never shows twenty distinct vehicles at once anyway.
 *
 * Carries the gradients across too - his cars are painted with them, and a
 * <use> whose fill points at a missing gradient renders black.
 */
const fs = require('fs');
const KEEP = process.argv.slice(2).length ? process.argv.slice(2) : [
  'Green_Car', 'Grey_Sadan', 'Red_Van', 'Brown_Jeep', 'Semitrailer',
  'Blue_Minivan', 'Yellow_Cab', 'Red_Sports_car', 'Blue_bus', 'Grey_Minivan'];

const src = fs.readFileSync('assets/js/cars-sprite.js', 'utf8');
const defs = /<defs id="grads">([\s\S]*?)<\/defs>/.exec(src)[1];
const sprite = src.slice(src.indexOf('<defs id="sprite">'));

/* pull each vehicle out by walking its <g> to the matching close */
function take(id) {
  const open = new RegExp('<g xmlns="[^"]*" id="' + id + '"[^>]*>');
  const m = open.exec(sprite);
  if (!m) throw new Error('no vehicle named ' + id);
  let i = m.index + m[0].length, depth = 1;
  const re = /<g\b[^>]*?(\/?)>|<\/g>/g;
  re.lastIndex = i;
  let t;
  while ((t = re.exec(sprite))) {
    if (t[0].startsWith('</g')) { if (--depth === 0) return sprite.slice(m.index, re.lastIndex); }
    else if (!t[1]) depth++;
  }
  throw new Error('unterminated ' + id);
}

const out = KEEP.map(take);
const body = out.join('\n');

/* KEEP ONLY THE GRADIENTS THESE TEN ACTUALLY USE. His defs block carries every
   gradient for all twenty, and a car painted with url(#missing) renders black -
   so this walks the references, including gradients that xlink to each other. */
const wanted = new Set();
let grew = true;
const grad = id => new RegExp('<(linearGradient|radialGradient)[^>]*\\bid="'
  + id.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '"[^>]*?(?:/>|>[\\s\\S]*?</\\1>)');
[...body.matchAll(/url\(#([^)]+)\)/g)].forEach(m => wanted.add(m[1]));
while (grew) {
  grew = false;
  for (const id of [...wanted]) {
    const m = grad(id).exec(defs);
    if (!m) continue;
    for (const r of [...m[0].matchAll(/(?:xlink:)?href="#([^"]+)"/g)])
      if (!wanted.has(r[1])) { wanted.add(r[1]); grew = true; }
  }
}
const keptDefs = [...wanted].map(id => (grad(id).exec(defs) || [''])[0]).join('');

/* A TEMPLATE LITERAL, NOT JSON. His SVG is almost all double-quoted attributes,
   and JSON.stringify escapes every one of them - which doubled the file. */
const esc = t => t.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
const js = '/* GENERATED by tools/subset_sprite.js - do not hand-edit.\n'
  + '   ' + KEEP.length + ' of his twenty vehicles, all drawn facing right, with\n'
  + '   only the gradients they reference. Blend modes are already inline CSS;\n'
  + '   see assets/js/cars-sprite.js for why that matters. */\n'
  + 'window.H19_SPRITE=`<defs>' + esc(keptDefs + body) + '</defs>`;\n'
  + 'window.H19_CARS=' + JSON.stringify(KEEP) + ';\n';
fs.writeFileSync('build/v2/sprite.js', js);
console.error(KEEP.length + ' vehicles -> build/v2/sprite.js  ' + (js.length/1024).toFixed(0) + 'KB');
